#!/usr/bin/env node
'use strict';

let crx = require('./index')
let u = crx.u

async function main() {
    let args = process.argv.slice(2)
    let useKms = args[0] === '--kms'
    if (useKms) args.shift()

    if (!args[0]) {
        u.err(`Usage: ${u.progname()} [--kms] <private.pem | kms-key-id> < file.zip

Options:
  --kms    Use AWS KMS for signing. The argument should be a KMS key ID,
           ARN, or alias (e.g., 'alias/my-signing-key').
           Requires AWS credentials to be configured.

Examples:
  ${u.progname()} private.pem < extension.zip > extension.crx
  ${u.progname()} --kms alias/chrome-signing-key < extension.zip > extension.crx`)
    }

    let kp, zip
    if (useKms) {
        const { KMSClient } = require('@aws-sdk/client-kms')
        const kmsClient = new KMSClient()
            ;[kp, zip] = await Promise.all([crx.kmsKeypair(kmsClient, args[0]), u.read()])
                .catch(u.err)
    } else {
        ;[kp, zip] = await Promise.all([crx.keypair(args[0]), u.read()])
            .catch(u.err)
    }

    let maker = new crx.Maker(kp, zip)
    process.stdout.write(await maker.creat())
}

main()
